version: '?'

services:
  database:
  image: postgres
  container_name: tutorial
  restart: always
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=database
  volumes:
    - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local